# Generated by Django 5.2.7 on 2025-12-13 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenBlacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jti",
                    models.CharField(
                        db_index=True,
                        help_text="Unique JWT ID (jti claim) to identify the token",
                        max_length=255,
                        unique=True,
                        verbose_name="JWT ID",
                    ),
                ),
                (
                    "blacklisted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when token was blacklisted",
                        verbose_name="blacklisted at",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expiration time - after this, the entry can be deleted",
                        verbose_name="token expiry time",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("logout", "User logged out"),
                            ("rotation", "Token rotated"),
                            ("revocation", "Token revoked by admin"),
                            ("password_change", "User changed password"),
                        ],
                        default="logout",
                        help_text="Reason for token blacklist",
                        max_length=50,
                        verbose_name="reason for blacklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who logged out or had token rotated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Blacklist",
                "verbose_name_plural": "Token Blacklists",
                "ordering": ["-blacklisted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "blacklisted_at"],
                        name="accounts_to_user_id_2b8ff4_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_to_expires_e3179c_idx"
                    ),
                ],
            },
        ),
    ]
